#TODO : <RAJESH + AISURYA> GUI AND TAKING INPUT
#TODO : <ALISHA> BCRYPT + PLUGIN + LINUX SCRIPT
#TODO : <SASWAT> OTP VERIFICATION ROUTINE
#TODO : <AISURYA> DEPLYOING FOR WINDOWS AND LINUX
#TODO : <RUDRA> ENCRYPTION AND DATA STORAGE
